#!/usr/bin/env python3
"""Ablation study generator for Cosmos Transfer 2.5.

Reads ablation.yaml, generates inference spec files for every combination
in the grid (prompts × controls × guidance × seeds), and writes a runner
script that feeds them all to inference in a single model-load.

Usage:
    python workspace/ablate.py                       # generate specs + run script
    python workspace/ablate.py --list                # preview the grid
    python workspace/ablate.py --run --gpus 8        # generate + execute
    python workspace/ablate.py --config other.yaml   # use a different config
"""

from __future__ import annotations

import argparse
import itertools
import json
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pyyaml is required: pip install pyyaml")

CONTROL_KEYS = ("edge", "depth", "vis", "seg")
BASE_PASSTHROUGH_KEYS = (
    "video_path",
    "negative_prompt",
    "num_steps",
    "resolution",
    "num_conditional_frames",
    "max_frames",
    "num_video_frames_per_chunk",
    "sigma_max",
    "show_control_condition",
    "show_input",
)

WORKSPACE = Path(__file__).resolve().parent
REPO_ROOT = WORKSPACE.parent


# ── Config loading ───────────────────────────────────────────────


def load_config(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


# ── Grid generation ──────────────────────────────────────────────


def _as_list(val):
    return val if isinstance(val, list) else [val]


def build_matrix(config: dict) -> list[tuple[str, dict]]:
    """Return a list of (name, spec_dict) for every point in the grid."""
    base = config.get("base", {})
    prompts = config.get("prompts", {})
    controls = config.get("controls", {})
    guidances = _as_list(config.get("sweep_guidance", base.get("guidance", 3)))
    seeds = _as_list(config.get("sweep_seed", base.get("seed", 42)))

    if not prompts:
        sys.exit("Error: define at least one entry under 'prompts:' in the config")
    if not controls:
        sys.exit("Error: define at least one entry under 'controls:' in the config")

    multi_g = len(guidances) > 1
    multi_s = len(seeds) > 1

    results: list[tuple[str, dict]] = []
    for (p_name, p_text), (c_name, c_cfg), g, s in itertools.product(
        prompts.items(), controls.items(), guidances, seeds,
    ):
        parts = [p_name, c_name]
        if multi_g:
            parts.append(f"g{g}")
        if multi_s:
            parts.append(f"s{s}")
        name = "__".join(parts)

        spec: dict = {
            "name": name,
            "prompt": p_text.strip(),
            "guidance": g,
            "seed": s,
        }

        for k in BASE_PASSTHROUGH_KEYS:
            if k in base:
                spec[k] = base[k]

        for k, v in c_cfg.items():
            spec[k] = v

        results.append((name, spec))

    return results


# ── File writers ─────────────────────────────────────────────────


def generate(config: dict) -> tuple[list[Path], Path]:
    """Write individual JSON specs and a combined JSONL. Returns paths."""
    specs = build_matrix(config)
    spec_dir = WORKSPACE / "specs"
    spec_dir.mkdir(parents=True, exist_ok=True)

    json_paths: list[Path] = []
    jsonl_lines: list[str] = []

    for name, spec in specs:
        p = spec_dir / f"{name}.json"
        p.write_text(json.dumps(spec, indent=4) + "\n")
        json_paths.append(p)
        jsonl_lines.append(json.dumps(spec))

    jsonl_path = spec_dir / "all.jsonl"
    jsonl_path.write_text("\n".join(jsonl_lines) + "\n")

    return json_paths, jsonl_path


def write_run_script(jsonl_path: Path) -> Path:
    """Write a bash script that launches inference on all specs."""
    rel_jsonl = jsonl_path.relative_to(REPO_ROOT)
    rel_output = (WORKSPACE / "outputs").relative_to(REPO_ROOT)

    script = WORKSPACE / "run_ablation.sh"
    script.write_text(
        f"""\
#!/bin/bash
# Auto-generated by ablate.py — run from the repo root
# Usage: bash {script.relative_to(REPO_ROOT)} [NUM_GPUS]
set -e

GPUS=${{1:-1}}

if [ "$GPUS" -gt 1 ]; then
    torchrun --nproc_per_node="$GPUS" --master_port=12341 \\
        examples/inference.py -i {rel_jsonl} -o {rel_output}
else
    python examples/inference.py -i {rel_jsonl} -o {rel_output}
fi
"""
    )
    script.chmod(0o755)
    return script


# ── CLI ──────────────────────────────────────────────────────────


def print_grid(specs: list[tuple[str, dict]]) -> None:
    print(f"\n  Ablation grid: {len(specs)} spec(s)\n")
    for name, spec in specs:
        ctrls = [k for k in CONTROL_KEYS if k in spec]
        weights = ", ".join(
            f"{k}={spec[k].get('control_weight', 1.0)}" for k in ctrls
        )
        prompt_short = spec["prompt"].replace("\n", " ")[:80]
        print(f"  {name}")
        print(f"    controls : {weights}")
        print(f"    guidance : {spec['guidance']}   seed: {spec['seed']}")
        print(f"    prompt   : \"{prompt_short}...\"")
        print()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Ablation study generator for Cosmos Transfer 2.5",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=WORKSPACE / "ablation.yaml",
        help="Path to ablation YAML config (default: workspace/ablation.yaml)",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Preview the grid without generating files",
    )
    parser.add_argument(
        "--run",
        action="store_true",
        help="Generate specs and immediately run inference",
    )
    parser.add_argument(
        "--gpus",
        type=int,
        default=1,
        help="Number of GPUs (used with --run or in the generated script)",
    )
    args = parser.parse_args()

    config = load_config(args.config)
    specs = build_matrix(config)

    if args.list:
        print_grid(specs)
        return

    json_paths, jsonl_path = generate(config)
    script = write_run_script(jsonl_path)

    print(f"\n  Generated {len(json_paths)} spec(s) → workspace/specs/")
    print(f"  Combined JSONL    → {jsonl_path.relative_to(REPO_ROOT)}")
    print(f"  Run script        → {script.relative_to(REPO_ROOT)}")
    print(f"\n  To run on cluster:")
    print(f"    bash {script.relative_to(REPO_ROOT)} [NUM_GPUS]")
    print()

    if args.run:
        cmd = ["bash", str(script), str(args.gpus)]
        subprocess.run(cmd, cwd=str(REPO_ROOT), check=True)


if __name__ == "__main__":
    main()
